version: '3.9'

services:
  redis:
    image: redis:7
    container_name: redis
    ports:
      - "6379:6379"

  redpanda:
    image: docker.redpanda.com/redpandadata/redpanda:v23.3.10
    container_name: redpanda
    command:
      - redpanda
      - start
      - --smp=1
      - --memory=512M
      - --overprovisioned
      - --node-id=0
      - --check=false
      - --kafka-addr=PLAINTEXT://0.0.0.0:9092
      - --advertise-kafka-addr=PLAINTEXT://redpanda:9092
    ports:
      - "9092:9092"

  server1:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: server1
    environment:
      - KAFKA_BROKER=redpanda:9092
      - REDIS_URL=redis://redis:6379
      - PORT=3000 
    depends_on:
      - redis
      - redpanda
    expose:
      - "3000"

  server2:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: server2
    environment:
      - KAFKA_BROKER=redpanda:9092
      - REDIS_URL=redis://redis:6379
      - PORT=3001
    depends_on:
      - redis
      - redpanda
    expose:
      - "3001"

  nginx:
    image: nginx:latest
    ports:
      - "8080:8080"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/nginx-chat.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - server1
      - server2
